/*
 * API 2.0
 * Early release of version 2.0 of the Vend API.
 *
 * OpenAPI spec version: 2.0
 * Contact: api@vendhq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.vendhq.models2;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Consignment
 */

public class Consignment {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("outlet_id")
  private String outletId = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("consignment_date")
  private String consignmentDate = null;

  @JsonProperty("due_at")
  private String dueAt = null;

  @JsonProperty("received_at")
  private String receivedAt = null;

  @JsonProperty("type")
  private String type = null;

  @JsonProperty("status")
  private String status = null;

  @JsonProperty("supplier_id")
  private String supplierId = null;

  @JsonProperty("source_outlet_id")
  private String sourceOutletId = null;

  @JsonProperty("supplier_invoice")
  private String supplierInvoice = null;

  @JsonProperty("reference")
  private String reference = null;

  @JsonProperty("total_cost_gain")
  private Double totalCostGain = null;

  @JsonProperty("total_count_loss")
  private Double totalCountLoss = null;

  @JsonProperty("total_cost_loss")
  private Double totalCostLoss = null;

  @JsonProperty("created_at")
  private String createdAt = null;

  @JsonProperty("updated_at")
  private String updatedAt = null;

  @JsonProperty("deleted_at")
  private String deletedAt = null;

  @JsonProperty("version")
  private Integer version = null;

  @JsonProperty("total_count_gain")
  private Double totalCountGain = null;

  public Consignment id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Auto-generated object ID.
   * @return id
  **/
  @ApiModelProperty(value = "Auto-generated object ID.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Consignment outletId(String outletId) {
    this.outletId = outletId;
    return this;
  }

   /**
   * A valid ID of an outlet where stock will be received.
   * @return outletId
  **/
  @ApiModelProperty(value = "A valid ID of an outlet where stock will be received.")
  public String getOutletId() {
    return outletId;
  }

  public void setOutletId(String outletId) {
    this.outletId = outletId;
  }

  public Consignment name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Tue 29 Nov 2016 (string) - Consignment name.
   * @return name
  **/
  @ApiModelProperty(value = "Tue 29 Nov 2016 (string) - Consignment name.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Consignment consignmentDate(String consignmentDate) {
    this.consignmentDate = consignmentDate;
    return this;
  }

   /**
   * 11-28T19:02:15+00:00 (timestamp) - Consignment creation date.
   * @return consignmentDate
  **/
  @ApiModelProperty(value = "11-28T19:02:15+00:00 (timestamp) - Consignment creation date.")
  public String getConsignmentDate() {
    return consignmentDate;
  }

  public void setConsignmentDate(String consignmentDate) {
    this.consignmentDate = consignmentDate;
  }

  public Consignment dueAt(String dueAt) {
    this.dueAt = dueAt;
    return this;
  }

   /**
   * 11-30T19:08:541+00:00 (timestamp) - Due date.
   * @return dueAt
  **/
  @ApiModelProperty(value = "11-30T19:08:541+00:00 (timestamp) - Due date.")
  public String getDueAt() {
    return dueAt;
  }

  public void setDueAt(String dueAt) {
    this.dueAt = dueAt;
  }

  public Consignment receivedAt(String receivedAt) {
    this.receivedAt = receivedAt;
    return this;
  }

   /**
   * 11-30T19:08:541+00:00 (timestamp) - The date when consignment was received.
   * @return receivedAt
  **/
  @ApiModelProperty(value = "11-30T19:08:541+00:00 (timestamp) - The date when consignment was received.")
  public String getReceivedAt() {
    return receivedAt;
  }

  public void setReceivedAt(String receivedAt) {
    this.receivedAt = receivedAt;
  }

  public Consignment type(String type) {
    this.type = type;
    return this;
  }

   /**
   * One of &#x60;SUPPLIER&#x60;, &#x60;OUTLET&#x60;, &#x60;STOCKTAKE&#x60;, &#x60;RETURN&#x60;.
   * @return type
  **/
  @ApiModelProperty(value = "One of `SUPPLIER`, `OUTLET`, `STOCKTAKE`, `RETURN`.")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public Consignment status(String status) {
    this.status = status;
    return this;
  }

   /**
   * One of &#x60;OPEN&#x60;, &#x60;RECEIVED&#x60;, &#x60;SENT&#x60;, &#x60;STOCKTAKE&#x60;, &#x60;STOCKTAKE_SCHEDULED&#x60;, &#x60;STOCKTAKE_IN_PROGRESS&#x60;, &#x60;STOCKTAKE_IN_PROGRESS_PROCESSED&#x60;, &#x60;STOCKTAKE_COMPLETE&#x60;, &#x60;CLOSED&#x60;, &#x60;CANCELLED&#x60;
   * @return status
  **/
  @ApiModelProperty(value = "One of `OPEN`, `RECEIVED`, `SENT`, `STOCKTAKE`, `STOCKTAKE_SCHEDULED`, `STOCKTAKE_IN_PROGRESS`, `STOCKTAKE_IN_PROGRESS_PROCESSED`, `STOCKTAKE_COMPLETE`, `CLOSED`, `CANCELLED`")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public Consignment supplierId(String supplierId) {
    this.supplierId = supplierId;
    return this;
  }

   /**
   * a valid supplier ID.
   * @return supplierId
  **/
  @ApiModelProperty(value = "a valid supplier ID.")
  public String getSupplierId() {
    return supplierId;
  }

  public void setSupplierId(String supplierId) {
    this.supplierId = supplierId;
  }

  public Consignment sourceOutletId(String sourceOutletId) {
    this.sourceOutletId = sourceOutletId;
    return this;
  }

   /**
   * A valid ID of an outlet where stock will come from. **Stock transfers only**.
   * @return sourceOutletId
  **/
  @ApiModelProperty(value = "A valid ID of an outlet where stock will come from. **Stock transfers only**.")
  public String getSourceOutletId() {
    return sourceOutletId;
  }

  public void setSourceOutletId(String sourceOutletId) {
    this.sourceOutletId = sourceOutletId;
  }

  public Consignment supplierInvoice(String supplierInvoice) {
    this.supplierInvoice = supplierInvoice;
    return this;
  }

   /**
   * Supplier invoice number.
   * @return supplierInvoice
  **/
  @ApiModelProperty(value = "Supplier invoice number.")
  public String getSupplierInvoice() {
    return supplierInvoice;
  }

  public void setSupplierInvoice(String supplierInvoice) {
    this.supplierInvoice = supplierInvoice;
  }

  public Consignment reference(String reference) {
    this.reference = reference;
    return this;
  }

   /**
   * Order number.+ &#x60;total_count_gain&#x60; (number)
   * @return reference
  **/
  @ApiModelProperty(value = "Order number.+ `total_count_gain` (number)")
  public String getReference() {
    return reference;
  }

  public void setReference(String reference) {
    this.reference = reference;
  }

  public Consignment totalCostGain(Double totalCostGain) {
    this.totalCostGain = totalCostGain;
    return this;
  }

   /**
   * The cost of items over the expected level.
   * @return totalCostGain
  **/
  @ApiModelProperty(value = "The cost of items over the expected level.")
  public Double getTotalCostGain() {
    return totalCostGain;
  }

  public void setTotalCostGain(Double totalCostGain) {
    this.totalCostGain = totalCostGain;
  }

  public Consignment totalCountLoss(Double totalCountLoss) {
    this.totalCountLoss = totalCountLoss;
    return this;
  }

   /**
   * The number of items below the expected level.
   * @return totalCountLoss
  **/
  @ApiModelProperty(value = "The number of items below the expected level.")
  public Double getTotalCountLoss() {
    return totalCountLoss;
  }

  public void setTotalCountLoss(Double totalCountLoss) {
    this.totalCountLoss = totalCountLoss;
  }

  public Consignment totalCostLoss(Double totalCostLoss) {
    this.totalCostLoss = totalCostLoss;
    return this;
  }

   /**
   * The cost of items below the expected level.
   * @return totalCostLoss
  **/
  @ApiModelProperty(value = "The cost of items below the expected level.")
  public Double getTotalCostLoss() {
    return totalCostLoss;
  }

  public void setTotalCostLoss(Double totalCostLoss) {
    this.totalCostLoss = totalCostLoss;
  }

  public Consignment createdAt(String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Creation timestamp in UTC.
   * @return createdAt
  **/
  @ApiModelProperty(value = "Creation timestamp in UTC.")
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  public Consignment updatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Last update timestamp in UTC.
   * @return updatedAt
  **/
  @ApiModelProperty(value = "Last update timestamp in UTC.")
  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }

  public Consignment deletedAt(String deletedAt) {
    this.deletedAt = deletedAt;
    return this;
  }

   /**
   * Deletion timestamp in UTC.
   * @return deletedAt
  **/
  @ApiModelProperty(value = "Deletion timestamp in UTC.")
  public String getDeletedAt() {
    return deletedAt;
  }

  public void setDeletedAt(String deletedAt) {
    this.deletedAt = deletedAt;
  }

  public Consignment version(Integer version) {
    this.version = version;
    return this;
  }

   /**
   * Auto-incrementing object version number.
   * @return version
  **/
  @ApiModelProperty(value = "Auto-incrementing object version number.")
  public Integer getVersion() {
    return version;
  }

  public void setVersion(Integer version) {
    this.version = version;
  }

  public Consignment totalCountGain(Double totalCountGain) {
    this.totalCountGain = totalCountGain;
    return this;
  }

   /**
   * The number of items over the expected level.
   * @return totalCountGain
  **/
  @ApiModelProperty(value = "The number of items over the expected level.")
  public Double getTotalCountGain() {
    return totalCountGain;
  }

  public void setTotalCountGain(Double totalCountGain) {
    this.totalCountGain = totalCountGain;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Consignment consignment = (Consignment) o;
    return Objects.equals(this.id, consignment.id) &&
        Objects.equals(this.outletId, consignment.outletId) &&
        Objects.equals(this.name, consignment.name) &&
        Objects.equals(this.consignmentDate, consignment.consignmentDate) &&
        Objects.equals(this.dueAt, consignment.dueAt) &&
        Objects.equals(this.receivedAt, consignment.receivedAt) &&
        Objects.equals(this.type, consignment.type) &&
        Objects.equals(this.status, consignment.status) &&
        Objects.equals(this.supplierId, consignment.supplierId) &&
        Objects.equals(this.sourceOutletId, consignment.sourceOutletId) &&
        Objects.equals(this.supplierInvoice, consignment.supplierInvoice) &&
        Objects.equals(this.reference, consignment.reference) &&
        Objects.equals(this.totalCostGain, consignment.totalCostGain) &&
        Objects.equals(this.totalCountLoss, consignment.totalCountLoss) &&
        Objects.equals(this.totalCostLoss, consignment.totalCostLoss) &&
        Objects.equals(this.createdAt, consignment.createdAt) &&
        Objects.equals(this.updatedAt, consignment.updatedAt) &&
        Objects.equals(this.deletedAt, consignment.deletedAt) &&
        Objects.equals(this.version, consignment.version) &&
        Objects.equals(this.totalCountGain, consignment.totalCountGain);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, outletId, name, consignmentDate, dueAt, receivedAt, type, status, supplierId, sourceOutletId, supplierInvoice, reference, totalCostGain, totalCountLoss, totalCostLoss, createdAt, updatedAt, deletedAt, version, totalCountGain);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Consignment {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    outletId: ").append(toIndentedString(outletId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    consignmentDate: ").append(toIndentedString(consignmentDate)).append("\n");
    sb.append("    dueAt: ").append(toIndentedString(dueAt)).append("\n");
    sb.append("    receivedAt: ").append(toIndentedString(receivedAt)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    supplierId: ").append(toIndentedString(supplierId)).append("\n");
    sb.append("    sourceOutletId: ").append(toIndentedString(sourceOutletId)).append("\n");
    sb.append("    supplierInvoice: ").append(toIndentedString(supplierInvoice)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("    totalCostGain: ").append(toIndentedString(totalCostGain)).append("\n");
    sb.append("    totalCountLoss: ").append(toIndentedString(totalCountLoss)).append("\n");
    sb.append("    totalCostLoss: ").append(toIndentedString(totalCostLoss)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    deletedAt: ").append(toIndentedString(deletedAt)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    totalCountGain: ").append(toIndentedString(totalCountGain)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

