/*
 * API 2.0
 * Early release of version 2.0 of the Vend API.
 *
 * OpenAPI spec version: 2.0
 * Contact: api@vendhq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.vendhq.models2;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.vendhq.models2.InventoryCountItem;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * ConsignmentProductCollection
 */

public class ConsignmentProductCollection {
  @JsonProperty("data")
  private List<InventoryCountItem> data = null;

  public ConsignmentProductCollection data(List<InventoryCountItem> data) {
    this.data = data;
    return this;
  }

  public ConsignmentProductCollection addDataItem(InventoryCountItem dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<InventoryCountItem>();
    }
    this.data.add(dataItem);
    return this;
  }

   /**
   * An array of consignment products.
   * @return data
  **/
  @ApiModelProperty(value = "An array of consignment products.")
  public List<InventoryCountItem> getData() {
    return data;
  }

  public void setData(List<InventoryCountItem> data) {
    this.data = data;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConsignmentProductCollection consignmentProductCollection = (ConsignmentProductCollection) o;
    return Objects.equals(this.data, consignmentProductCollection.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(data);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConsignmentProductCollection {\n");
    
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

