/*
 * API 2.0
 * Early release of version 2.0 of the Vend API.
 *
 * OpenAPI spec version: 2.0
 * Contact: api@vendhq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.vendhq.models2;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.UUID;

/**
 * OutletTax
 */

public class OutletTax {
  @JsonProperty("outlet_id")
  private UUID outletId = null;

  @JsonProperty("product_id")
  private UUID productId = null;

  @JsonProperty("tax_id")
  private UUID taxId = null;

  @JsonProperty("deleted_at")
  private String deletedAt = null;

  @JsonProperty("version")
  private Integer version = null;

  public OutletTax outletId(UUID outletId) {
    this.outletId = outletId;
    return this;
  }

   /**
   * The ID of the outlet this record is associated with.
   * @return outletId
  **/
  @ApiModelProperty(required = true, value = "The ID of the outlet this record is associated with.")
  public UUID getOutletId() {
    return outletId;
  }

  public void setOutletId(UUID outletId) {
    this.outletId = outletId;
  }

  public OutletTax productId(UUID productId) {
    this.productId = productId;
    return this;
  }

   /**
   * The ID of the product this record is associated with.
   * @return productId
  **/
  @ApiModelProperty(required = true, value = "The ID of the product this record is associated with.")
  public UUID getProductId() {
    return productId;
  }

  public void setProductId(UUID productId) {
    this.productId = productId;
  }

  public OutletTax taxId(UUID taxId) {
    this.taxId = taxId;
    return this;
  }

   /**
   * The ID of the tax this record is associated with.
   * @return taxId
  **/
  @ApiModelProperty(required = true, value = "The ID of the tax this record is associated with.")
  public UUID getTaxId() {
    return taxId;
  }

  public void setTaxId(UUID taxId) {
    this.taxId = taxId;
  }

  public OutletTax deletedAt(String deletedAt) {
    this.deletedAt = deletedAt;
    return this;
  }

   /**
   * Deletion timestamp in UTC.
   * @return deletedAt
  **/
  @ApiModelProperty(value = "Deletion timestamp in UTC.")
  public String getDeletedAt() {
    return deletedAt;
  }

  public void setDeletedAt(String deletedAt) {
    this.deletedAt = deletedAt;
  }

  public OutletTax version(Integer version) {
    this.version = version;
    return this;
  }

   /**
   * Auto-incrementing object version number.
   * @return version
  **/
  @ApiModelProperty(required = true, value = "Auto-incrementing object version number.")
  public Integer getVersion() {
    return version;
  }

  public void setVersion(Integer version) {
    this.version = version;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OutletTax outletTax = (OutletTax) o;
    return Objects.equals(this.outletId, outletTax.outletId) &&
        Objects.equals(this.productId, outletTax.productId) &&
        Objects.equals(this.taxId, outletTax.taxId) &&
        Objects.equals(this.deletedAt, outletTax.deletedAt) &&
        Objects.equals(this.version, outletTax.version);
  }

  @Override
  public int hashCode() {
    return Objects.hash(outletId, productId, taxId, deletedAt, version);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OutletTax {\n");
    
    sb.append("    outletId: ").append(toIndentedString(outletId)).append("\n");
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("    taxId: ").append(toIndentedString(taxId)).append("\n");
    sb.append("    deletedAt: ").append(toIndentedString(deletedAt)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

