/*
 * API 2.0
 * Early release of version 2.0 of the Vend API.
 *
 * OpenAPI spec version: 2.0
 * Contact: api@vendhq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.vendhq.models2;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * SaleTax
 */

public class SaleTax {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("rate")
  private Double rate = null;

  @JsonProperty("amount")
  private Double amount = null;

  public SaleTax name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Tax name.
   * @return name
  **/
  @ApiModelProperty(value = "Tax name.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public SaleTax rate(Double rate) {
    this.rate = rate;
    return this;
  }

   /**
   * Tax rate.
   * @return rate
  **/
  @ApiModelProperty(value = "Tax rate.")
  public Double getRate() {
    return rate;
  }

  public void setRate(Double rate) {
    this.rate = rate;
  }

  public SaleTax amount(Double amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Tax amount.
   * @return amount
  **/
  @ApiModelProperty(value = "Tax amount.")
  public Double getAmount() {
    return amount;
  }

  public void setAmount(Double amount) {
    this.amount = amount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SaleTax saleTax = (SaleTax) o;
    return Objects.equals(this.name, saleTax.name) &&
        Objects.equals(this.rate, saleTax.rate) &&
        Objects.equals(this.amount, saleTax.amount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, rate, amount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SaleTax {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    rate: ").append(toIndentedString(rate)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

