/*
 * API 2.0
 * Early release of version 2.0 of the Vend API.
 *
 * OpenAPI spec version: 2.0
 * Contact: api@vendhq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.vendhq.models2;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.vendhq.models2.TaxRate;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * Tax
 */

public class Tax {
  @JsonProperty("id")
  private UUID id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("version")
  private Integer version = null;

  @JsonProperty("deleted_at")
  private String deletedAt = null;

  @JsonProperty("rates")
  private List<TaxRate> rates = null;

  @JsonProperty("is_default")
  private Boolean isDefault = null;

  @JsonProperty("display_name")
  private String displayName = null;

  public Tax id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * Auto-generated object ID.
   * @return id
  **/
  @ApiModelProperty(required = true, value = "Auto-generated object ID.")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public Tax name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the tax.
   * @return name
  **/
  @ApiModelProperty(value = "The name of the tax.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Tax version(Integer version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getVersion() {
    return version;
  }

  public void setVersion(Integer version) {
    this.version = version;
  }

  public Tax deletedAt(String deletedAt) {
    this.deletedAt = deletedAt;
    return this;
  }

   /**
   * The deletion timestamp.
   * @return deletedAt
  **/
  @ApiModelProperty(required = true, value = "The deletion timestamp.")
  public String getDeletedAt() {
    return deletedAt;
  }

  public void setDeletedAt(String deletedAt) {
    this.deletedAt = deletedAt;
  }

  public Tax rates(List<TaxRate> rates) {
    this.rates = rates;
    return this;
  }

  public Tax addRatesItem(TaxRate ratesItem) {
    if (this.rates == null) {
      this.rates = new ArrayList<TaxRate>();
    }
    this.rates.add(ratesItem);
    return this;
  }

   /**
   * Get rates
   * @return rates
  **/
  @ApiModelProperty(value = "")
  public List<TaxRate> getRates() {
    return rates;
  }

  public void setRates(List<TaxRate> rates) {
    this.rates = rates;
  }

  public Tax isDefault(Boolean isDefault) {
    this.isDefault = isDefault;
    return this;
  }

   /**
   * Indicates whether the tax is used as the default one.
   * @return isDefault
  **/
  @ApiModelProperty(required = true, value = "Indicates whether the tax is used as the default one.")
  public Boolean isIsDefault() {
    return isDefault;
  }

  public void setIsDefault(Boolean isDefault) {
    this.isDefault = isDefault;
  }

  public Tax displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * The name of the tax used for display.
   * @return displayName
  **/
  @ApiModelProperty(required = true, value = "The name of the tax used for display.")
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Tax tax = (Tax) o;
    return Objects.equals(this.id, tax.id) &&
        Objects.equals(this.name, tax.name) &&
        Objects.equals(this.version, tax.version) &&
        Objects.equals(this.deletedAt, tax.deletedAt) &&
        Objects.equals(this.rates, tax.rates) &&
        Objects.equals(this.isDefault, tax.isDefault) &&
        Objects.equals(this.displayName, tax.displayName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, version, deletedAt, rates, isDefault, displayName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Tax {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    deletedAt: ").append(toIndentedString(deletedAt)).append("\n");
    sb.append("    rates: ").append(toIndentedString(rates)).append("\n");
    sb.append("    isDefault: ").append(toIndentedString(isDefault)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

