/*
 * API 2.0
 * Early release of version 2.0 of the Vend API.
 *
 * OpenAPI spec version: 2.0
 * Contact: api@vendhq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.vendhq.models_2;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * PaymentTypeConfig
 */

public class PaymentTypeConfig {
  @JsonProperty("url")
  private String url = null;

  @JsonProperty("print")
  private Boolean print = null;

  public PaymentTypeConfig url(String url) {
    this.url = url;
    return this;
  }

   /**
   * The URL of  the gateway.
   * @return url
  **/
  @ApiModelProperty(value = "The URL of  the gateway.")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public PaymentTypeConfig print(Boolean print) {
    this.print = print;
    return this;
  }

   /**
   * Indicates whether a receipt will be printed???
   * @return print
  **/
  @ApiModelProperty(value = "Indicates whether a receipt will be printed???")
  public Boolean getPrint() {
    return print;
  }

  public void setPrint(Boolean print) {
    this.print = print;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentTypeConfig paymentTypeConfig = (PaymentTypeConfig) o;
    return Objects.equals(this.url, paymentTypeConfig.url) &&
        Objects.equals(this.print, paymentTypeConfig.print);
  }

  @Override
  public int hashCode() {
    return Objects.hash(url, print);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentTypeConfig {\n");
    
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    print: ").append(toIndentedString(print)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

