/*
 * API 2.0
 * Early release of version 2.0 of the Vend API.
 *
 * OpenAPI spec version: 2.0
 * Contact: api@vendhq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.vendhq.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * An object representing a single channel.
 */
@ApiModel(description = "An object representing a single channel.")

public class Channel {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("store_url")
  private String storeUrl = null;

  /**
   * The type of channel this is.
   */
  public enum ChannelTypeEnum {
    WOOCOMMERCE("woocommerce");

    private String value;

    ChannelTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ChannelTypeEnum fromValue(String text) {
      for (ChannelTypeEnum b : ChannelTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("channel_type")
  private ChannelTypeEnum channelType = null;

  @JsonProperty("register_id")
  private String registerId = null;

  @JsonProperty("payment_type_id")
  private String paymentTypeId = null;

  @JsonProperty("inventory_outlet_ids")
  private List<String> inventoryOutletIds = new ArrayList<>();

  @JsonProperty("created_at")
  private OffsetDateTime createdAt = null;

  @JsonProperty("sales_last_imported_at")
  private OffsetDateTime salesLastImportedAt = null;

  @JsonProperty("products_last_imported_at")
  private OffsetDateTime productsLastImportedAt = null;

  public Channel id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Auto-generated object ID.
   * @return id
  **/
  @ApiModelProperty(required = true, value = "Auto-generated object ID.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Channel storeUrl(String storeUrl) {
    this.storeUrl = storeUrl;
    return this;
  }

   /**
   * The store identifier.
   * @return storeUrl
  **/
  @ApiModelProperty(required = true, value = "The store identifier.")
  public String getStoreUrl() {
    return storeUrl;
  }

  public void setStoreUrl(String storeUrl) {
    this.storeUrl = storeUrl;
  }

  public Channel channelType(ChannelTypeEnum channelType) {
    this.channelType = channelType;
    return this;
  }

   /**
   * The type of channel this is.
   * @return channelType
  **/
  @ApiModelProperty(required = true, value = "The type of channel this is.")
  public ChannelTypeEnum getChannelType() {
    return channelType;
  }

  public void setChannelType(ChannelTypeEnum channelType) {
    this.channelType = channelType;
  }

  public Channel registerId(String registerId) {
    this.registerId = registerId;
    return this;
  }

   /**
   * The Vend register id that sales will be associated to.
   * @return registerId
  **/
  @ApiModelProperty(required = true, value = "The Vend register id that sales will be associated to.")
  public String getRegisterId() {
    return registerId;
  }

  public void setRegisterId(String registerId) {
    this.registerId = registerId;
  }

  public Channel paymentTypeId(String paymentTypeId) {
    this.paymentTypeId = paymentTypeId;
    return this;
  }

   /**
   * The Vend payment type id that sale payments will be associated to.
   * @return paymentTypeId
  **/
  @ApiModelProperty(required = true, value = "The Vend payment type id that sale payments will be associated to.")
  public String getPaymentTypeId() {
    return paymentTypeId;
  }

  public void setPaymentTypeId(String paymentTypeId) {
    this.paymentTypeId = paymentTypeId;
  }

  public Channel inventoryOutletIds(List<String> inventoryOutletIds) {
    this.inventoryOutletIds = inventoryOutletIds;
    return this;
  }

  public Channel addInventoryOutletIdsItem(String inventoryOutletIdsItem) {
    this.inventoryOutletIds.add(inventoryOutletIdsItem);
    return this;
  }

   /**
   * The Vend outlet ids that count towards inventory.
   * @return inventoryOutletIds
  **/
  @ApiModelProperty(required = true, value = "The Vend outlet ids that count towards inventory.")
  public List<String> getInventoryOutletIds() {
    return inventoryOutletIds;
  }

  public void setInventoryOutletIds(List<String> inventoryOutletIds) {
    this.inventoryOutletIds = inventoryOutletIds;
  }

  public Channel createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * An RFC3339 representation of the time at which the channel was created.
   * @return createdAt
  **/
  @ApiModelProperty(value = "An RFC3339 representation of the time at which the channel was created.")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public Channel salesLastImportedAt(OffsetDateTime salesLastImportedAt) {
    this.salesLastImportedAt = salesLastImportedAt;
    return this;
  }

   /**
   * An RFC3339 representation of the time at which sales were last imported.
   * @return salesLastImportedAt
  **/
  @ApiModelProperty(required = true, value = "An RFC3339 representation of the time at which sales were last imported.")
  public OffsetDateTime getSalesLastImportedAt() {
    return salesLastImportedAt;
  }

  public void setSalesLastImportedAt(OffsetDateTime salesLastImportedAt) {
    this.salesLastImportedAt = salesLastImportedAt;
  }

  public Channel productsLastImportedAt(OffsetDateTime productsLastImportedAt) {
    this.productsLastImportedAt = productsLastImportedAt;
    return this;
  }

   /**
   * An RFC3339 representation of the time at which products were last imported.
   * @return productsLastImportedAt
  **/
  @ApiModelProperty(required = true, value = "An RFC3339 representation of the time at which products were last imported.")
  public OffsetDateTime getProductsLastImportedAt() {
    return productsLastImportedAt;
  }

  public void setProductsLastImportedAt(OffsetDateTime productsLastImportedAt) {
    this.productsLastImportedAt = productsLastImportedAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Channel channel = (Channel) o;
    return Objects.equals(this.id, channel.id) &&
        Objects.equals(this.storeUrl, channel.storeUrl) &&
        Objects.equals(this.channelType, channel.channelType) &&
        Objects.equals(this.registerId, channel.registerId) &&
        Objects.equals(this.paymentTypeId, channel.paymentTypeId) &&
        Objects.equals(this.inventoryOutletIds, channel.inventoryOutletIds) &&
        Objects.equals(this.createdAt, channel.createdAt) &&
        Objects.equals(this.salesLastImportedAt, channel.salesLastImportedAt) &&
        Objects.equals(this.productsLastImportedAt, channel.productsLastImportedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, storeUrl, channelType, registerId, paymentTypeId, inventoryOutletIds, createdAt, salesLastImportedAt, productsLastImportedAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Channel {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    storeUrl: ").append(toIndentedString(storeUrl)).append("\n");
    sb.append("    channelType: ").append(toIndentedString(channelType)).append("\n");
    sb.append("    registerId: ").append(toIndentedString(registerId)).append("\n");
    sb.append("    paymentTypeId: ").append(toIndentedString(paymentTypeId)).append("\n");
    sb.append("    inventoryOutletIds: ").append(toIndentedString(inventoryOutletIds)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    salesLastImportedAt: ").append(toIndentedString(salesLastImportedAt)).append("\n");
    sb.append("    productsLastImportedAt: ").append(toIndentedString(productsLastImportedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

