/*
 * API 2.0
 * Early release of version 2.0 of the Vend API.
 *
 * OpenAPI spec version: 2.0
 * Contact: api@vendhq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.vendhq.models;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.UUID;

/**
 * Image
 */

public class Image {
  @JsonProperty("id")
  private UUID id = null;

  @JsonProperty("version")
  private Long version = null;

  @JsonProperty("product_id")
  private UUID productId = null;

  @JsonProperty("position")
  private Double position = null;

  @JsonProperty("status")
  private String status = null;

  public Image id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * Auto-generated object ID.
   * @return id
  **/
  @ApiModelProperty(value = "Auto-generated object ID.")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public Image version(Long version) {
    this.version = version;
    return this;
  }

   /**
   * Auto-incrementing object version number.
   * @return version
  **/
  @ApiModelProperty(value = "Auto-incrementing object version number.")
  public Long getVersion() {
    return version;
  }

  public void setVersion(Long version) {
    this.version = version;
  }

  public Image productId(UUID productId) {
    this.productId = productId;
    return this;
  }

   /**
   * The ID of the product this image is associated with.
   * @return productId
  **/
  @ApiModelProperty(value = "The ID of the product this image is associated with.")
  public UUID getProductId() {
    return productId;
  }

  public void setProductId(UUID productId) {
    this.productId = productId;
  }

  public Image position(Double position) {
    this.position = position;
    return this;
  }

   /**
   * Position of the image in collection of images associated with a product.
   * @return position
  **/
  @ApiModelProperty(value = "Position of the image in collection of images associated with a product.")
  public Double getPosition() {
    return position;
  }

  public void setPosition(Double position) {
    this.position = position;
  }

  public Image status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Status if the image upload processing. Can be &#x60;processing&#x60;, &#x60;uploaded&#x60;, &#x60;error&#x60;.
   * @return status
  **/
  @ApiModelProperty(value = "Status if the image upload processing. Can be `processing`, `uploaded`, `error`.")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Image image = (Image) o;
    return Objects.equals(this.id, image.id) &&
        Objects.equals(this.version, image.version) &&
        Objects.equals(this.productId, image.productId) &&
        Objects.equals(this.position, image.position) &&
        Objects.equals(this.status, image.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, version, productId, position, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Image {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("    position: ").append(toIndentedString(position)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

