/*
 * API 2.0
 * Early release of version 2.0 of the Vend API.
 *
 * OpenAPI spec version: 2.0
 * Contact: api@vendhq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.vendhq.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.UUID;

/**
 * InventoryCountFilter
 */

public class InventoryCountFilter {
  @JsonProperty("type")
  private String type = null;

  @JsonProperty("value")
  private UUID value = null;

  public InventoryCountFilter type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Filter type. One of &#x60;product_type&#x60;, &#x60;brand&#x60;, &#x60;supplier&#x60;, &#x60;tag&#x60;, &#x60;product&#x60;.
   * @return type
  **/
  @ApiModelProperty(required = true, value = "Filter type. One of `product_type`, `brand`, `supplier`, `tag`, `product`.")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public InventoryCountFilter value(UUID value) {
    this.value = value;
    return this;
  }

   /**
   * The ID of the filter object.
   * @return value
  **/
  @ApiModelProperty(required = true, value = "The ID of the filter object.")
  public UUID getValue() {
    return value;
  }

  public void setValue(UUID value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InventoryCountFilter inventoryCountFilter = (InventoryCountFilter) o;
    return Objects.equals(this.type, inventoryCountFilter.type) &&
        Objects.equals(this.value, inventoryCountFilter.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InventoryCountFilter {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

