/*
 * API 2.0
 * Early release of version 2.0 of the Vend API.
 *
 * OpenAPI spec version: 2.0
 * Contact: api@vendhq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.vendhq.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Inventory
 */

public class Inventory {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("product_id")
  private String productId = null;

  @JsonProperty("outlet_id")
  private String outletId = null;

  @JsonProperty("inventory_level")
  private Double inventoryLevel = null;

  @JsonProperty("reorder_point")
  private Double reorderPoint = null;

  @JsonProperty("reorder_amount")
  private Double reorderAmount = null;

  public Inventory id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Auto-generated object ID.
   * @return id
  **/
  @ApiModelProperty(value = "Auto-generated object ID.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Inventory productId(String productId) {
    this.productId = productId;
    return this;
  }

   /**
   * The ID of the product associated with this inventory record.
   * @return productId
  **/
  @ApiModelProperty(value = "The ID of the product associated with this inventory record.")
  public String getProductId() {
    return productId;
  }

  public void setProductId(String productId) {
    this.productId = productId;
  }

  public Inventory outletId(String outletId) {
    this.outletId = outletId;
    return this;
  }

   /**
   * The ID of the outlet associated with this inventory record.
   * @return outletId
  **/
  @ApiModelProperty(value = "The ID of the outlet associated with this inventory record.")
  public String getOutletId() {
    return outletId;
  }

  public void setOutletId(String outletId) {
    this.outletId = outletId;
  }

  public Inventory inventoryLevel(Double inventoryLevel) {
    this.inventoryLevel = inventoryLevel;
    return this;
  }

   /**
   * Current inventory level.
   * @return inventoryLevel
  **/
  @ApiModelProperty(value = "Current inventory level.")
  public Double getInventoryLevel() {
    return inventoryLevel;
  }

  public void setInventoryLevel(Double inventoryLevel) {
    this.inventoryLevel = inventoryLevel;
  }

  public Inventory reorderPoint(Double reorderPoint) {
    this.reorderPoint = reorderPoint;
    return this;
  }

   /**
   * Level at which a product should be automatically included in stock orders.
   * @return reorderPoint
  **/
  @ApiModelProperty(value = "Level at which a product should be automatically included in stock orders.")
  public Double getReorderPoint() {
    return reorderPoint;
  }

  public void setReorderPoint(Double reorderPoint) {
    this.reorderPoint = reorderPoint;
  }

  public Inventory reorderAmount(Double reorderAmount) {
    this.reorderAmount = reorderAmount;
    return this;
  }

   /**
   * Amount to be added to the automatic stock order.
   * @return reorderAmount
  **/
  @ApiModelProperty(value = "Amount to be added to the automatic stock order.")
  public Double getReorderAmount() {
    return reorderAmount;
  }

  public void setReorderAmount(Double reorderAmount) {
    this.reorderAmount = reorderAmount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Inventory inventory = (Inventory) o;
    return Objects.equals(this.id, inventory.id) &&
        Objects.equals(this.productId, inventory.productId) &&
        Objects.equals(this.outletId, inventory.outletId) &&
        Objects.equals(this.inventoryLevel, inventory.inventoryLevel) &&
        Objects.equals(this.reorderPoint, inventory.reorderPoint) &&
        Objects.equals(this.reorderAmount, inventory.reorderAmount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, productId, outletId, inventoryLevel, reorderPoint, reorderAmount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Inventory {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("    outletId: ").append(toIndentedString(outletId)).append("\n");
    sb.append("    inventoryLevel: ").append(toIndentedString(inventoryLevel)).append("\n");
    sb.append("    reorderPoint: ").append(toIndentedString(reorderPoint)).append("\n");
    sb.append("    reorderAmount: ").append(toIndentedString(reorderAmount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

