/*
 * API 2.0
 * Early release of version 2.0 of the Vend API.
 *
 * OpenAPI spec version: 2.0
 * Contact: api@vendhq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.vendhq.models;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Outlet
 */

public class Outlet {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("time_zone")
  private String timeZone = null;

  @JsonProperty("default_tax_id")
  private String defaultTaxId = null;

  @JsonProperty("currency")
  private String currency = null;

  @JsonProperty("currency_symbol")
  private String currencySymbol = null;

  @JsonProperty("display_prices")
  private String displayPrices = null;

  @JsonProperty("physical_address_1")
  private String physicalAddress1 = null;

  @JsonProperty("physical_address_2")
  private String physicalAddress2 = null;

  @JsonProperty("physical_suburb")
  private String physicalSuburb = null;

  @JsonProperty("physical_city")
  private String physicalCity = null;

  @JsonProperty("physical_postcode")
  private String physicalPostcode = null;

  @JsonProperty("physical_state")
  private String physicalState = null;

  @JsonProperty("physical_country_id")
  private String physicalCountryId = null;

  @JsonProperty("deleted_at")
  private String deletedAt = null;

  @JsonProperty("version")
  private Long version = null;

  public Outlet id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Auto-generated object ID.
   * @return id
  **/
  @ApiModelProperty(value = "Auto-generated object ID.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Outlet name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The outlet name.
   * @return name
  **/
  @ApiModelProperty(value = "The outlet name.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Outlet timeZone(String timeZone) {
    this.timeZone = timeZone;
    return this;
  }

   /**
   * Outlet timezone. **read only**
   * @return timeZone
  **/
  @ApiModelProperty(value = "Outlet timezone. **read only**")
  public String getTimeZone() {
    return timeZone;
  }

  public void setTimeZone(String timeZone) {
    this.timeZone = timeZone;
  }

  public Outlet defaultTaxId(String defaultTaxId) {
    this.defaultTaxId = defaultTaxId;
    return this;
  }

   /**
   * Default tax id used for sales in this outlet. **deprecated**
   * @return defaultTaxId
  **/
  @ApiModelProperty(value = "Default tax id used for sales in this outlet. **deprecated**")
  public String getDefaultTaxId() {
    return defaultTaxId;
  }

  public void setDefaultTaxId(String defaultTaxId) {
    this.defaultTaxId = defaultTaxId;
  }

  public Outlet currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Currency name.
   * @return currency
  **/
  @ApiModelProperty(value = "Currency name.")
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public Outlet currencySymbol(String currencySymbol) {
    this.currencySymbol = currencySymbol;
    return this;
  }

   /**
   * Currency symbol.
   * @return currencySymbol
  **/
  @ApiModelProperty(value = "Currency symbol.")
  public String getCurrencySymbol() {
    return currencySymbol;
  }

  public void setCurrencySymbol(String currencySymbol) {
    this.currencySymbol = currencySymbol;
  }

  public Outlet displayPrices(String displayPrices) {
    this.displayPrices = displayPrices;
    return this;
  }

   /**
   * Indicates whether prices in this outlet should be displayed as tax-inclusive.
   * @return displayPrices
  **/
  @ApiModelProperty(value = "Indicates whether prices in this outlet should be displayed as tax-inclusive.")
  public String getDisplayPrices() {
    return displayPrices;
  }

  public void setDisplayPrices(String displayPrices) {
    this.displayPrices = displayPrices;
  }

  public Outlet physicalAddress1(String physicalAddress1) {
    this.physicalAddress1 = physicalAddress1;
    return this;
  }

   /**
   * Physical address, line 1.
   * @return physicalAddress1
  **/
  @ApiModelProperty(value = "Physical address, line 1.")
  public String getPhysicalAddress1() {
    return physicalAddress1;
  }

  public void setPhysicalAddress1(String physicalAddress1) {
    this.physicalAddress1 = physicalAddress1;
  }

  public Outlet physicalAddress2(String physicalAddress2) {
    this.physicalAddress2 = physicalAddress2;
    return this;
  }

   /**
   * Physical address, line 2.
   * @return physicalAddress2
  **/
  @ApiModelProperty(value = "Physical address, line 2.")
  public String getPhysicalAddress2() {
    return physicalAddress2;
  }

  public void setPhysicalAddress2(String physicalAddress2) {
    this.physicalAddress2 = physicalAddress2;
  }

  public Outlet physicalSuburb(String physicalSuburb) {
    this.physicalSuburb = physicalSuburb;
    return this;
  }

   /**
   * Physical address, suburb.
   * @return physicalSuburb
  **/
  @ApiModelProperty(value = "Physical address, suburb.")
  public String getPhysicalSuburb() {
    return physicalSuburb;
  }

  public void setPhysicalSuburb(String physicalSuburb) {
    this.physicalSuburb = physicalSuburb;
  }

  public Outlet physicalCity(String physicalCity) {
    this.physicalCity = physicalCity;
    return this;
  }

   /**
   * Physical address, city.
   * @return physicalCity
  **/
  @ApiModelProperty(value = "Physical address, city.")
  public String getPhysicalCity() {
    return physicalCity;
  }

  public void setPhysicalCity(String physicalCity) {
    this.physicalCity = physicalCity;
  }

  public Outlet physicalPostcode(String physicalPostcode) {
    this.physicalPostcode = physicalPostcode;
    return this;
  }

   /**
   * Physical address, post code.
   * @return physicalPostcode
  **/
  @ApiModelProperty(value = "Physical address, post code.")
  public String getPhysicalPostcode() {
    return physicalPostcode;
  }

  public void setPhysicalPostcode(String physicalPostcode) {
    this.physicalPostcode = physicalPostcode;
  }

  public Outlet physicalState(String physicalState) {
    this.physicalState = physicalState;
    return this;
  }

   /**
   * Physical address, state.
   * @return physicalState
  **/
  @ApiModelProperty(value = "Physical address, state.")
  public String getPhysicalState() {
    return physicalState;
  }

  public void setPhysicalState(String physicalState) {
    this.physicalState = physicalState;
  }

  public Outlet physicalCountryId(String physicalCountryId) {
    this.physicalCountryId = physicalCountryId;
    return this;
  }

   /**
   * Physical address, country code.
   * @return physicalCountryId
  **/
  @ApiModelProperty(value = "Physical address, country code.")
  public String getPhysicalCountryId() {
    return physicalCountryId;
  }

  public void setPhysicalCountryId(String physicalCountryId) {
    this.physicalCountryId = physicalCountryId;
  }

  public Outlet deletedAt(String deletedAt) {
    this.deletedAt = deletedAt;
    return this;
  }

   /**
   * Deletion timestamp in UTC.
   * @return deletedAt
  **/
  @ApiModelProperty(value = "Deletion timestamp in UTC.")
  public String getDeletedAt() {
    return deletedAt;
  }

  public void setDeletedAt(String deletedAt) {
    this.deletedAt = deletedAt;
  }

  public Outlet version(Long version) {
    this.version = version;
    return this;
  }

   /**
   * Auto-incrementing object version number.
   * @return version
  **/
  @ApiModelProperty(value = "Auto-incrementing object version number.")
  public Long getVersion() {
    return version;
  }

  public void setVersion(Long version) {
    this.version = version;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Outlet outlet = (Outlet) o;
    return Objects.equals(this.id, outlet.id) &&
        Objects.equals(this.name, outlet.name) &&
        Objects.equals(this.timeZone, outlet.timeZone) &&
        Objects.equals(this.defaultTaxId, outlet.defaultTaxId) &&
        Objects.equals(this.currency, outlet.currency) &&
        Objects.equals(this.currencySymbol, outlet.currencySymbol) &&
        Objects.equals(this.displayPrices, outlet.displayPrices) &&
        Objects.equals(this.physicalAddress1, outlet.physicalAddress1) &&
        Objects.equals(this.physicalAddress2, outlet.physicalAddress2) &&
        Objects.equals(this.physicalSuburb, outlet.physicalSuburb) &&
        Objects.equals(this.physicalCity, outlet.physicalCity) &&
        Objects.equals(this.physicalPostcode, outlet.physicalPostcode) &&
        Objects.equals(this.physicalState, outlet.physicalState) &&
        Objects.equals(this.physicalCountryId, outlet.physicalCountryId) &&
        Objects.equals(this.deletedAt, outlet.deletedAt) &&
        Objects.equals(this.version, outlet.version);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, timeZone, defaultTaxId, currency, currencySymbol, displayPrices, physicalAddress1, physicalAddress2, physicalSuburb, physicalCity, physicalPostcode, physicalState, physicalCountryId, deletedAt, version);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Outlet {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    timeZone: ").append(toIndentedString(timeZone)).append("\n");
    sb.append("    defaultTaxId: ").append(toIndentedString(defaultTaxId)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    currencySymbol: ").append(toIndentedString(currencySymbol)).append("\n");
    sb.append("    displayPrices: ").append(toIndentedString(displayPrices)).append("\n");
    sb.append("    physicalAddress1: ").append(toIndentedString(physicalAddress1)).append("\n");
    sb.append("    physicalAddress2: ").append(toIndentedString(physicalAddress2)).append("\n");
    sb.append("    physicalSuburb: ").append(toIndentedString(physicalSuburb)).append("\n");
    sb.append("    physicalCity: ").append(toIndentedString(physicalCity)).append("\n");
    sb.append("    physicalPostcode: ").append(toIndentedString(physicalPostcode)).append("\n");
    sb.append("    physicalState: ").append(toIndentedString(physicalState)).append("\n");
    sb.append("    physicalCountryId: ").append(toIndentedString(physicalCountryId)).append("\n");
    sb.append("    deletedAt: ").append(toIndentedString(deletedAt)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

