/*
 * API 2.0
 * Early release of version 2.0 of the Vend API.
 *
 * OpenAPI spec version: 2.0
 * Contact: api@vendhq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.vendhq.models;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Payment
 */

public class Payment {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("register_id")
  private String registerId = null;

  @JsonProperty("retailer_payment_type_id")
  private String retailerPaymentTypeId = null;

  @JsonProperty("payment_type_id")
  private String paymentTypeId = null;

  @JsonProperty("payment_date")
  private String paymentDate = null;

  @JsonProperty("amount")
  private Double amount = null;

  public Payment name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Payment type name.
   * @return name
  **/
  @ApiModelProperty(value = "Payment type name.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Payment registerId(String registerId) {
    this.registerId = registerId;
    return this;
  }

   /**
   * A valid register ID.
   * @return registerId
  **/
  @ApiModelProperty(value = "A valid register ID.")
  public String getRegisterId() {
    return registerId;
  }

  public void setRegisterId(String registerId) {
    this.registerId = registerId;
  }

  public Payment retailerPaymentTypeId(String retailerPaymentTypeId) {
    this.retailerPaymentTypeId = retailerPaymentTypeId;
    return this;
  }

   /**
   * A valid retailer payment type ID.
   * @return retailerPaymentTypeId
  **/
  @ApiModelProperty(value = "A valid retailer payment type ID.")
  public String getRetailerPaymentTypeId() {
    return retailerPaymentTypeId;
  }

  public void setRetailerPaymentTypeId(String retailerPaymentTypeId) {
    this.retailerPaymentTypeId = retailerPaymentTypeId;
  }

  public Payment paymentTypeId(String paymentTypeId) {
    this.paymentTypeId = paymentTypeId;
    return this;
  }

   /**
   * A payment type associated with the retailer payment type. **deprecated** ???
   * @return paymentTypeId
  **/
  @ApiModelProperty(value = "A payment type associated with the retailer payment type. **deprecated** ???")
  public String getPaymentTypeId() {
    return paymentTypeId;
  }

  public void setPaymentTypeId(String paymentTypeId) {
    this.paymentTypeId = paymentTypeId;
  }

  public Payment paymentDate(String paymentDate) {
    this.paymentDate = paymentDate;
    return this;
  }

   /**
   * Payment date in UTC.
   * @return paymentDate
  **/
  @ApiModelProperty(value = "Payment date in UTC.")
  public String getPaymentDate() {
    return paymentDate;
  }

  public void setPaymentDate(String paymentDate) {
    this.paymentDate = paymentDate;
  }

  public Payment amount(Double amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Payment amount.
   * @return amount
  **/
  @ApiModelProperty(value = "Payment amount.")
  public Double getAmount() {
    return amount;
  }

  public void setAmount(Double amount) {
    this.amount = amount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Payment payment = (Payment) o;
    return Objects.equals(this.name, payment.name) &&
        Objects.equals(this.registerId, payment.registerId) &&
        Objects.equals(this.retailerPaymentTypeId, payment.retailerPaymentTypeId) &&
        Objects.equals(this.paymentTypeId, payment.paymentTypeId) &&
        Objects.equals(this.paymentDate, payment.paymentDate) &&
        Objects.equals(this.amount, payment.amount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, registerId, retailerPaymentTypeId, paymentTypeId, paymentDate, amount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Payment {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    registerId: ").append(toIndentedString(registerId)).append("\n");
    sb.append("    retailerPaymentTypeId: ").append(toIndentedString(retailerPaymentTypeId)).append("\n");
    sb.append("    paymentTypeId: ").append(toIndentedString(paymentTypeId)).append("\n");
    sb.append("    paymentDate: ").append(toIndentedString(paymentDate)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

