/*
 * API 2.0
 * Early release of version 2.0 of the Vend API.
 *
 * OpenAPI spec version: 2.0
 * Contact: api@vendhq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.vendhq.models;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.vendhq.models.CustomerGroup;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * PriceBook
 */

public class PriceBook {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("customer_group_id")
  private String customerGroupId = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("valid_from")
  private String validFrom = null;

  @JsonProperty("valid_to")
  private String validTo = null;

  @JsonProperty("restrict_to_platform_key")
  private String restrictToPlatformKey = null;

  @JsonProperty("outlet_id")
  private String outletId = null;

  @JsonProperty("restrict_to_platform_label")
  private String restrictToPlatformLabel = null;

  @JsonProperty("customer_group")
  private CustomerGroup customerGroup = null;

  @JsonProperty("version")
  private Double version = null;

  @JsonProperty("deleted_at")
  private String deletedAt = null;

  public PriceBook name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Price book name.
   * @return name
  **/
  @ApiModelProperty(required = true, value = "Price book name.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public PriceBook customerGroupId(String customerGroupId) {
    this.customerGroupId = customerGroupId;
    return this;
  }

   /**
   * The ID of the customer group
   * @return customerGroupId
  **/
  @ApiModelProperty(required = true, value = "The ID of the customer group")
  public String getCustomerGroupId() {
    return customerGroupId;
  }

  public void setCustomerGroupId(String customerGroupId) {
    this.customerGroupId = customerGroupId;
  }

  public PriceBook id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Auto-generated object ID.
   * @return id
  **/
  @ApiModelProperty(value = "Auto-generated object ID.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public PriceBook validFrom(String validFrom) {
    this.validFrom = validFrom;
    return this;
  }

   /**
   * The date when the price book becomes valid (active).
   * @return validFrom
  **/
  @ApiModelProperty(value = "The date when the price book becomes valid (active).")
  public String getValidFrom() {
    return validFrom;
  }

  public void setValidFrom(String validFrom) {
    this.validFrom = validFrom;
  }

  public PriceBook validTo(String validTo) {
    this.validTo = validTo;
    return this;
  }

   /**
   * The date when the price book becomes invalid (inactive).
   * @return validTo
  **/
  @ApiModelProperty(value = "The date when the price book becomes invalid (inactive).")
  public String getValidTo() {
    return validTo;
  }

  public void setValidTo(String validTo) {
    this.validTo = validTo;
  }

  public PriceBook restrictToPlatformKey(String restrictToPlatformKey) {
    this.restrictToPlatformKey = restrictToPlatformKey;
    return this;
  }

   /**
   * &#x60;\&quot;0\&quot;&#x60; - all platforms, &#x60;\&quot;1\&quot;&#x60; - in store, &#x60;\&quot;2\&quot;&#x60; - ecommerce.
   * @return restrictToPlatformKey
  **/
  @ApiModelProperty(value = "`\"0\"` - all platforms, `\"1\"` - in store, `\"2\"` - ecommerce.")
  public String getRestrictToPlatformKey() {
    return restrictToPlatformKey;
  }

  public void setRestrictToPlatformKey(String restrictToPlatformKey) {
    this.restrictToPlatformKey = restrictToPlatformKey;
  }

  public PriceBook outletId(String outletId) {
    this.outletId = outletId;
    return this;
  }

   /**
   * The ID of an outlet for which the price book should be used.+ type: GENERAL (string) - Internal value. Safe to ignore.
   * @return outletId
  **/
  @ApiModelProperty(value = "The ID of an outlet for which the price book should be used.+ type: GENERAL (string) - Internal value. Safe to ignore.")
  public String getOutletId() {
    return outletId;
  }

  public void setOutletId(String outletId) {
    this.outletId = outletId;
  }

  public PriceBook restrictToPlatformLabel(String restrictToPlatformLabel) {
    this.restrictToPlatformLabel = restrictToPlatformLabel;
    return this;
  }

   /**
   * One of &#x60;In Store&#x60;, &#x60;Ecommerce&#x60;, &#x60;All Platforms&#x60;.
   * @return restrictToPlatformLabel
  **/
  @ApiModelProperty(value = "One of `In Store`, `Ecommerce`, `All Platforms`.")
  public String getRestrictToPlatformLabel() {
    return restrictToPlatformLabel;
  }

  public void setRestrictToPlatformLabel(String restrictToPlatformLabel) {
    this.restrictToPlatformLabel = restrictToPlatformLabel;
  }

  public PriceBook customerGroup(CustomerGroup customerGroup) {
    this.customerGroup = customerGroup;
    return this;
  }

   /**
   * Get customerGroup
   * @return customerGroup
  **/
  @ApiModelProperty(value = "")
  public CustomerGroup getCustomerGroup() {
    return customerGroup;
  }

  public void setCustomerGroup(CustomerGroup customerGroup) {
    this.customerGroup = customerGroup;
  }

  public PriceBook version(Double version) {
    this.version = version;
    return this;
  }

   /**
   * Auto-incrementing object version number.
   * @return version
  **/
  @ApiModelProperty(value = "Auto-incrementing object version number.")
  public Double getVersion() {
    return version;
  }

  public void setVersion(Double version) {
    this.version = version;
  }

  public PriceBook deletedAt(String deletedAt) {
    this.deletedAt = deletedAt;
    return this;
  }

   /**
   * Deletion timestamp in UTC.
   * @return deletedAt
  **/
  @ApiModelProperty(value = "Deletion timestamp in UTC.")
  public String getDeletedAt() {
    return deletedAt;
  }

  public void setDeletedAt(String deletedAt) {
    this.deletedAt = deletedAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PriceBook priceBook = (PriceBook) o;
    return Objects.equals(this.name, priceBook.name) &&
        Objects.equals(this.customerGroupId, priceBook.customerGroupId) &&
        Objects.equals(this.id, priceBook.id) &&
        Objects.equals(this.validFrom, priceBook.validFrom) &&
        Objects.equals(this.validTo, priceBook.validTo) &&
        Objects.equals(this.restrictToPlatformKey, priceBook.restrictToPlatformKey) &&
        Objects.equals(this.outletId, priceBook.outletId) &&
        Objects.equals(this.restrictToPlatformLabel, priceBook.restrictToPlatformLabel) &&
        Objects.equals(this.customerGroup, priceBook.customerGroup) &&
        Objects.equals(this.version, priceBook.version) &&
        Objects.equals(this.deletedAt, priceBook.deletedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, customerGroupId, id, validFrom, validTo, restrictToPlatformKey, outletId, restrictToPlatformLabel, customerGroup, version, deletedAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PriceBook {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    customerGroupId: ").append(toIndentedString(customerGroupId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    validFrom: ").append(toIndentedString(validFrom)).append("\n");
    sb.append("    validTo: ").append(toIndentedString(validTo)).append("\n");
    sb.append("    restrictToPlatformKey: ").append(toIndentedString(restrictToPlatformKey)).append("\n");
    sb.append("    outletId: ").append(toIndentedString(outletId)).append("\n");
    sb.append("    restrictToPlatformLabel: ").append(toIndentedString(restrictToPlatformLabel)).append("\n");
    sb.append("    customerGroup: ").append(toIndentedString(customerGroup)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    deletedAt: ").append(toIndentedString(deletedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

